name: alias
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  auto_route: ^2.3.2
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.2.0
  freezed_annotation: ^0.14.3
  json_annotation: ^4.1.0

dev_dependencies:
  auto_route_generator: ^2.3.2
  build_runner: ^2.1.2
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  freezed: ^0.14.5
  json_serializable: ^5.0.0

dependency_overrides:
  meta: ^1.4.0

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
